/**
 * Full IBAN country code data. Note that SEPA compliance and IBAN lengths
 * may change, so verify before using in financial applications. Rivo is not
 * responsible for any financial losses incurred by using this data.
 */
import type { IbanInfo } from "../types/iban";

export const ibanData: IbanInfo[] = [
  { country: "Albania", code: "AL", length: 28 },
  { country: "Andorra", code: "AD", length: 24 },
  { country: "Austria", code: "AT", length: 20 },
  { country: "Azerbaijan", code: "AZ", length: 28 },
  { country: "Bahrain", code: "BH", length: 22 },
  { country: "Belarus", code: "BY", length: 28 },
  { country: "Belgium", code: "BE", length: 16 },
  { country: "Bosnia and Herzegovina", code: "BA", length: 20 },
  { country: "Brazil", code: "BR", length: 29 },
  { country: "Bulgaria", code: "BG", length: 22 },
  { country: "Burundi", code: "BI", length: 27 },
  { country: "Costa Rica", code: "CR", length: 22 },
  { country: "Croatia", code: "HR", length: 21 },
  { country: "Cyprus", code: "CY", length: 28 },
  { country: "Czech Republic", code: "CZ", length: 24 },
  { country: "Denmark", code: "DK", length: 18 },
  { country: "Djibouti", code: "DJ", length: 27 },
  { country: "Dominican Republic", code: "DO", length: 28 },
  { country: "Egypt", code: "EG", length: 29 },
  { country: "El Salvador", code: "SV", length: 28 },
  { country: "Estonia", code: "EE", length: 20 },
  { country: "Falkland Islands", code: "FK", length: 18 },
  { country: "Faroe Islands", code: "FO", length: 18 },
  { country: "Finland", code: "FI", length: 18 },
  { country: "France", code: "FR", length: 27 },
  { country: "Georgia", code: "GE", length: 22 },
  { country: "Germany", code: "DE", length: 22 },
  { country: "Gibraltar", code: "GI", length: 23 },
  { country: "Greece", code: "GR", length: 27 },
  { country: "Greenland", code: "GL", length: 18 },
  { country: "Guatemala", code: "GT", length: 28 },
  { country: "Holy See", code: "VA", length: 22 },
  { country: "Hungary", code: "HU", length: 28 },
  { country: "Iceland", code: "IS", length: 26 },
  { country: "Iran", code: "IR", length: 26 },
  { country: "Iraq", code: "IQ", length: 23 },
  { country: "Ireland", code: "IE", length: 22 },
  { country: "Israel", code: "IL", length: 23 },
  { country: "Italy", code: "IT", length: 27 },
  { country: "Ivory Coast", code: "CI", length: 28 },
  { country: "Jordan", code: "JO", length: 30 },
  { country: "Kazakhstan", code: "KZ", length: 20 },
  { country: "Kosovo", code: "XK", length: 20 },
  { country: "Kuwait", code: "KW", length: 30 },
  { country: "Latvia", code: "LV", length: 21 },
  { country: "Lebanon", code: "LB", length: 28 },
  { country: "Liechtenstein", code: "LI", length: 21 },
  { country: "Lithuania", code: "LT", length: 20 },
  { country: "Luxembourg", code: "LU", length: 20 },
  { country: "Malta", code: "MT", length: 31 },
  { country: "Mauritania", code: "MR", length: 27 },
  { country: "Mauritius", code: "MU", length: 30 },
  { country: "Moldova", code: "MD", length: 24 },
  { country: "Monaco", code: "MC", length: 27 },
  { country: "Montenegro", code: "ME", length: 22 },
  { country: "Netherlands", code: "NL", length: 18 },
  { country: "North Macedonia", code: "MK", length: 19 },
  { country: "Norway", code: "NO", length: 15 },
  { country: "Oman", code: "OM", length: 23 },
  { country: "Pakistan", code: "PK", length: 24 },
  { country: "Palestine", code: "PS", length: 29 },
  { country: "Poland", code: "PL", length: 28 },
  { country: "Portugal", code: "PT", length: 25 },
  { country: "Qatar", code: "QA", length: 29 },
  { country: "Romania", code: "RO", length: 24 },
  { country: "San Marino", code: "SM", length: 27 },
  { country: "Saudi Arabia", code: "SA", length: 24 },
  { country: "Serbia", code: "RS", length: 22 },
  { country: "Slovakia", code: "SK", length: 24 },
  { country: "Slovenia", code: "SI", length: 19 },
  { country: "Spain", code: "ES", length: 24 },
  { country: "Sweden", code: "SE", length: 24 },
  { country: "Switzerland", code: "CH", length: 21 },
  { country: "Tunisia", code: "TN", length: 24 },
  { country: "Turkey", code: "TR", length: 26 },
  { country: "Ukraine", code: "UA", length: 29 },
  { country: "United Arab Emirates", code: "AE", length: 23 },
  { country: "United Kingdom", code: "GB", length: 22 },
  { country: "Virgin Islands (UK)", code: "VG", length: 24 },
  { country: "Yemen", code: "YE", length: 30 },
];
